$accent = rgba(237, 248, 249, 1.0)
$accent_two = rgba(194, 198, 204, 1.0)
$bg = rgba(15, 15, 15, 0.45)
$text = rgba(255, 255, 255, 1.0)
$text_dim = rgba(200, 200, 200, 0.75)
$border = rgba(255, 255, 255, 0.4)

general {
    no_fade_in = false
    disable_loading_bar = false
    hide_cursor = false
    ignore_empty_input = true
    immediate_render = true
}

background {
    path = /home/lzx/Pictures/Wallpaper/mac2.jpg  
    blur_brightness = 0.4000
    blur_passes = 1 
    blur_size = 7
    color = "black"
    fast_transition = true
}

label {
    monitor =
    text = Welcome back, lzx
    color = rgba(255,255,255,0.20)
    font_size = 16
    font_family = JetBrains Mono Nerd Font Medium
    position = 0, 200
    halign = center
    valign = center
    shadow_passes = 1
}

$time = cmd[update:1000] date +"%I:%M"
$second = cmd[update:1000] date + "%S"
$date = cmd[update:60000] date +"%A, %B %d"
$greet = cmd[update:60000] date +'Good %p, %u' | sed 's/AM/Morning/;s/PM/Afternoon/' # 简化逻辑

label {
    text = cmd[update:1000] date +"%I:%M"
    color = $accent
    font_size = 120
    font_family = JetBrains Mono Nerd Font ExtraBold
    position = -40, 100 # Shifted left slightly to make room for seconds
    halign = center
    valign = center
}

# SECONDS (Smaller and aligned to the right of the time)
label {
    text = cmd[update:1000] date +"%S"
    color = $accent_two
    font_size = 40 # Significantly smaller to maintain hierarchy
    font_family = JetBrains Mono Nerd Font ExtraBold
    position = 250, 75  # Adjusted to sit near the end of the time
    halign = center
    valign = center
}

label {
    text = $date
    color = $accent
    font_size = 22
    position = 0, -40
    halign = center
    valign = center
}

input-field {
    size = 280, 50
    outline_thickness = 2
    outer_color = $border
    inner_color = $bg
    font_color = $text
    placeholder_text = Enter Password
    position = 0, -280
    halign = center
    valign = center
}
