require("plugin.vscode")
require("plugin.alpha")
require("plugin.telescope")
require("plugin.undotree")
require("plugin.nvim-tree")
require("plugin.trim")
require("plugin.autopairs")
require("plugin.rainbow-delimiters")
require("plugin.nvim-highlight-colors")

require("plugin.mason-lspconfig")
require("plugin.nvim-lspconfig")
require("plugin.nvim-treesitter")
require("plugin.blinkcmp")
require("plugin.nvim-dap")
